// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkerService.Data;

#nullable disable

namespace WorkerService.Migrations
{
    [DbContext(typeof(CounterContext))]
    [Migration("20230528015441_initmg")]
    partial class initmg
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkerService.Models.Counter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Counter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cc69f92-015b-493f-9d14-59a99971e3f2"),
                            CreatedAt = new DateTime(2023, 5, 28, 1, 54, 41, 684, DateTimeKind.Utc).AddTicks(4449),
                            LastUpdatedTime = new DateTime(2023, 5, 28, 1, 54, 41, 684, DateTimeKind.Utc).AddTicks(4449),
                            Like = 0,
                            UpdatedBy = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
